components/selectArea.js

This PR addresses:
Limiting of 4 selections and alerting User.
To Test this PR:
Try to select more than 4 words that are not contiguous.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/versecheck/2)

Limit selections and alert user.

---

Container.js
components/checkArea.js
components/selectArea.js
utils/selectionHelpers.js

Updates to get Reducer Props rendering properly
Will require updating App, ScripturePane, translationWords, VerseCheck to the branch of the same name: `feature/update-reducer-props`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/versecheck/5)

Updates to get Reducer Props rendering properly

---

Container.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/versecheck/8)

Fix verseText lag

---

utils/selectionHelpers.js

Shouldn’t print to console when loading anymore.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/versecheck/9)

Commented out testing and console.log

---

Container.js
components/view.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/versecheck/10)

Reminders Implementation in the versecheck

---

components/DialogComponent.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/versecheck/17)

removed injectTapEventPlugin

---

Container.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/versecheck/18)

Added Check For Project Book Being Same as Context Id

---

Container.js

This pull request addresses the file editing feature. 
To test this pull request, test it with the branch `feature/ih-1043-verse-edit`, try with multiple verses.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/versecheck/15)

Implement file editing

---

components/DialogComponent.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/versecheck/19)

added e.preventDefault() to fix bug

---

components/MyLanguageModal.js
components/MyTargetVerse.js
components/selectArea.js

Addresses https://github.com/unfoldingWord-dev/translationCore/issues/1097
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/versecheck/24)

MyLanguageModal properly shows ltr/rtl languages now

---

components/selectArea.js

Addresses https://github.com/unfoldingWord-dev/translationCore/issues/1112
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/versecheck/25)

Target Language and Full Book Name

---

components/selectArea.js

This PR fixes bugs introduced after changing projects
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/versecheck/26)

Various Bug Fixes

---

components/View.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/versecheck/28)

Fixed capitalization of Style

---

components/SelectArea.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/versecheck/29)

Missed another ./css/sStyle reference, looked for others.

---

Container.js
components/ActionsArea.js
components/CommentArea.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/versecheck/30)

issue 1190, disable save until comment changes

---

Container.js
components/ActionsArea.js
components/CheckArea.js
components/EditVerseArea.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/versecheck/31)

issue 1191, workflow for editing verse

---

components/ActionsArea.js
components/SaveArea.js
components/View.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/versecheck/34)

Button styling

---

Container.js
components/DialogComponent.js
components/SelectArea.js

- Click on the `save & continue`  button with no selections. a dialog should pop up and its design should look like the style guide design for dialogs.
https://xd.adobe.com/view/0c5703e1-8ddb-4c25-b66f-933a9e014326/screen/64dbd6a8-71a7-45dd-b7ad-45df58185e97/Modals
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/versecheck/37)

Modified component dialog that handles skipping checks to look like the modal style guide

---

components/CheckArea.js
components/DirectionsArea.js
components/EditVerseArea.js
components/MyLanguageModal.js
components/SelectArea.js
css/Style.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/versecheck/36)

issue 1408, update styling of modal and colors

---

components/SelectArea.js
css/Style.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/versecheck/39)

Minor fix for scrolling

---

components/DialogComponent.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/versecheck/40)

fix for issue 1206

---

components/MyLanguageModal.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/versecheck/41)

fix for issue 1408

---

Container.js
components/SelectArea.js

To tes this PR, open a tool, and try doing some of the Verse Check functions while not logged in
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/versecheck/42)

Add check for logged in user for all VerseCheck functions

---

components/ActionsArea.js
components/View.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/versecheck/44)

Change colors

---

Container.js

This PR catches missing verses in Verse Check by replacing them with "". Test with a deleted chapter.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/versecheck/46)

Catch Missing Verses

---

components/MyLanguageModal.js
components/SelectArea.js
components/View.js
css/Style.js

Fixed centering of long text in "directions" area, added tool tips to expand icon and bookmark, updated close button on modal, etc
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/versecheck/48)

multiple formatting fixes

---

components/ActionsArea.js
components/DialogComponent.js
components/SaveArea.js
components/View.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/versecheck/49)

update colors and buttons

---

Container.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/versecheck/52)

removed showNotification action

---

Container.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/versecheck/54)

bible chapter breakdown

---

components/SelectArea.js

conditional select mode #1829
- Ensure select mode works properly.
- Make sure select/deselect mode does not work in edit verse and comment.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/versecheck/55)

conditional select mode #1829

---

Container.js
components/ActionsArea.js
components/IconIndicators.js
components/View.js
css/Style.js

**Added Verse check icon indicators & added bookmark toggle button**
- Open a tool make changes as verse edits, comments, selections and bookmarks and see them reflected in the icon indicators.
- New bookmark button added should work. 
- Bookmark toggle should be disabled when switching to a check that has no been bookmarked.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/versecheck/57)

Verse check icon indicators

---

Container.js
components/ActionsArea.js
components/CheckArea.js
components/CommentArea.js
components/DefaultArea.js
components/DirectionsArea.js
components/SelectionArea.js
css/Style.js

- Now you should not be able to make selections in the default text area
- To make a selection now you must click select.
- Instructions are above the selectable text.
- CommentMode & VerseEdit mode still work.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/versecheck/58)

New select mode implementation 

---

Container.js
components/ActionsArea.js
components/CheckArea.js
components/DefaultArea.js
components/DirectionsArea.js
components/SelectionArea.js
css/Style.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/versecheck/59)

Fixed QA issues for verse check (selection mode)

---

components/SaveArea.js
components/View.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/versecheck/60)

Now hiding previous and next buttons while in selection mode

---

components/DefaultArea.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/versecheck/61)

recovered no selection in verse check

---

Container.js
index.js
package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/versecheck/68)

Changed the way we export the namespace and container 

---

Container.js
components/CheckArea.js
components/DefaultArea.js
components/DirectionsArea.js
components/InstructionsArea.js
components/SelectionArea.js
components/View.js
css/Style.js
index.js
package.json

Refer to https://github.com/unfoldingWord-dev/translationCore/issues/2290 for specifications of requirements.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/versecheck/67)

UI Updates To Check Area

---

components/View.js

Changed text on headers for main mode and select mode.
Ensure they match as the story specifies.
https://github.com/unfoldingWord-dev/translationCore/issues/2465
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/versecheck/75)

Changed Verse Check Verbiage

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/versecheck/83)

 translationCore Updater commit update

---

src/helpers/windowSelectionHelpers.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/versecheck/88)

bugfix: overlapping with multiple occurrences

---

.eslintrc
__tests__/MyLanguageModal.test.js
__tests__/View.test.js
__tests__/__snapshots__/View.test.js.snap
__tests__/windowSelectionHelpers.test.js
src/Container.js
src/components/CheckArea.js
src/components/CommentArea.js
src/components/DefaultArea.js
src/components/DialogComponent.js
src/components/EditVerseArea.js
src/components/IconIndicators.js
src/components/InstructionsArea.js
src/components/MyLanguageModal.js
src/components/MyTargetVerse.js
src/components/RenderSelectionTextComponent.js
src/components/SaveArea.js
src/components/SelectionArea.js
src/components/View.js
src/helpers/stringHelpers.js
src/helpers/windowSelectionHelpers.js
src/utils/selectionHelpers.js

- Added support for bibles new data structure that uses `languageIds` to organize bibles.
- **Review** https://github.com/unfoldingWord-dev/translationCore/pull/3967 **first** 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/versecheck/91)

Added support for bibles new data structure that uses languageIds to organize bibles 

---

package.json
src/components/ActionsArea.js
src/components/RenderSelectionTextComponent.js
src/components/View.js
src/helpers/selectionHelpers.js

- This PR exchanges the package isEqual for deep-equal, per request of klappy from my PR regarding word alignment errors #3906.
run the following script in the root folder to get all the branches needed.
`git checkout feature-jay-3973 && git pull; cd tC_apps/ScripturePane; git checkout feature-jay-3973 && git pull; cd ../VerseCheck; git checkout feature-jay-3973 && git pull; cd ../wordAlignment; git checkout feature-jay-3973 && git pull; cd ../../;`
- Run the app and make sure everything works as expected
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/versecheck/92)

changed isEqual to deep-equal

---

src/components/DefaultArea.js
src/components/MyLanguageModal.js
src/components/MyTargetVerse.js
src/components/SelectionArea.js
src/helpers/windowSelectionHelpers.js

- 
-
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/versecheck/90)

Added Target Language Book name to project manifest and displaying it if found.

---

src/components/CheckArea.js

- This PR uses the selected gateway language to display for the selection instructions
- Run this command on the root folder
`runGitCommands() { git checkout feature-jay-3864 && git pull; }; runGitCommands; cd tC_apps/VerseCheck; runGitCommands; cd ../translationWords; runGitCommands; cd ../../; npm i; npm start;`
- Open any project new or old.
- Try the tW tool with the selected GL as both `English` and `Hindi`.
- Everything should work as expected.
- Ensure that in the instructions for tW you see the selected GL type for the quote. (Hindi or English)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/versecheck/93)

Select Translation For (GL Quote)

---

__tests__/__snapshots__/View.test.js.snap
__tests__/fixtures/project/loadedProjectShortened.json

- Updated reference from ULB to ULT
- **Test with:** https://github.com/unfoldingWord-dev/translationCore/pull/4081
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/versecheck/94)

Updated reference from ULB to ULT

---

src/Container.js

- Related to https://github.com/unfoldingWord-dev/translationCore/issues/2004#issuecomment-377988687 This fixes editing verses.
-
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/versecheck/101)

fixed editing verses
