Container.js
This should fix cases where props update and verseText isn’t updated.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/versecheck/7)
=> populate verseText when props change

Container.js
This PR adds a check on the render method in the case that the fetch data does not complete before the view is presented
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/versecheck/11)
=> Fix Non-USFM Project Loading

components/checkArea.js, components/editVerseArea.js
Addresses: https://github.com/unfoldingWord-dev/translationCore/issues/1094
How to test:
Load a project with a target language that is read from right to left. Edit a verse, it should now display properly in the text field.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/versecheck/21)
=> Edit verse area now knows what direction it is going

Container.js, components/selectArea.js
Invalidate Selections if occurrences don't match current count. It alerts the user so that they know their edit invalidated the selection that was previously made.
Checkout branch of the same name in translationCore app where the logic that is called resides. When rendering the text it validates to see if the selections are still valid.
Make a selection, then edit the verse and modify the words in the selection. Upon saving the verse edit, you should be alerted that the selection was invalidated.
Find a common place to check for this validation so that it doesn’t happen deep in the tool but somewhere at a higher level.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/ve …
=> Invalidate Selections if occurrences don't match current count.

Container.js, components/view.js
This issue was masking the fact that VerseEdit is not updating the application state's copy of the verse. Now that render is not using VerseCheck's state to display the verse, the edit looks like it did not take, but it did in the filesystem.
Edit a verse and/or comment, and they should still work. There are some cases where a bug in the toggle icons of the menu gets in the way but it happens without this PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/versecheck/22)
=> Don't use state to render the verse or comment.

Container.js, components/DialogAlert.js, components/view.js
**ISSUES ADDRESSED:**
- Added alert modal when clicking "save changes" without checking a checkbox.
- Fixed bug where editing a verse without making any change would delete the entire verse.
**TEST:**
- Click the edit button and once in the edit mode try saving without checking a checkbox. an alert dialog should pop up, wich should close on close button click. then when you select a checkbox the pop-up should not open.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/versecheck/23)
=> In edit mode, require a checkbox to be selected before "Save Changes" can be clicked 

components/MyTargetVerse.js
Addresses QA concerns on https://github.com/unfoldingWord-dev/translationCore/issues/1097
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/versecheck/33)
=> Showing verse/chapter where applicable in modal now

components/SelectArea.js
Addresses https://github.com/unfoldingWord-dev/translationCore/issues/1332
Minor styling changes. Make a verse really long by editing it and it should scroll now instead of getting gigantic.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/versecheck/35)
=> Added styling that prevents the select area from getting too big

components/CommentArea.js, components/EditVerseArea.js
Addresses https://github.com/unfoldingWord-dev/translationCore/issues/1405
Click edit or comment, the cursor should automatically go inside of the text box now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/versecheck/38)
=> Focus the text boxes on edit or comment

components/SelectArea.js
This addresses https://github.com/unfoldingWord-dev/translationCore/issues/1336
How to test this:
1. Load a project and tool
2. Make a selection on any check
3. Click on "edit" or "comment"
4. Try and modify the selection while editing or commenting on the verse
5. You should no longer be able to.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/versecheck/43)
=> Disable selection in comment/edit

Container.js, components/SelectArea.js, utils/selectionHelpers.js
1. Find a verse with multiple occurrences of a word. 
2. Select a word before any of those occurrences.
3. Select the last occurrence.
4. Deselect and keep trying to break it.
5. Edit a verse and add more than one space in a phrase.
6. Save it, make a selection that transcends where the whitespace was added.
7. Verify that it worked.
8. Repeat with a line break.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/versecheck/45)
=> Working complicated selections

components/SelectArea.js
Fix selection validation from firing improperly
Make selections and use all forms of navigation back and forth to ensure selections are not made invalid unless the text was edited and no longer valid.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/versecheck/50)
=> Fix selection validation from firing improperly

Container.js
You now confirm if you want to save a blank verse and it should save.
- Edit a verse to blank text box.
- Click reason to edit.
- Click Save.
- Click Cancel and it should return to edit.
- Click Save.
- Click Save Blank Verse and it should save.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/versecheck/53)
=> Confirm Blank Verse #1818

components/CheckArea.js, components/DefaultArea.js
This PR makes the select mode area the only place where a user can select/highlight when using the checking tool.
#2306
`git checkout enhancement/jay/remove-highlight/2295`
Try highlighting the areas specified in #2295 and make sure they are not selectable/highlightable
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/versecheck/62)
=> Remove Highlighting From Verse Check When Not Applicable

Container.js, components/ActionsArea.js, components/DefaultArea.js, components/SelectionArea.js
Please review with https://github.com/unfoldingWord-dev/translationCore/pull/2412
- Updated params reference
- Changed the button to just Save for verse edits #2294
https://github.com/unfoldingWord-dev/translationCore/issues/2294
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/versecheck/63)
=> updated params reference and update `save changes` button to just `save`

css/Style.js
- Open a check with a verse that overflows the left panel of the verseCheck and verify that it doesn't overflow but instead a scrollbar shows up.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/versecheck/64)
=> Text no longer overflows left panel of select area

components/EditVerseArea.js
- Open any project and go to the verse edit area in the verse check adjust the width of the tC app window and the reason codes should not overlap.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/versecheck/65)
=> fixed Overlapping of reason codes on verse edit

components/EditVerseArea.js
- Reason codes on verse edit should not overlap
- Open the verse edit area and make sure the reason codes don't overlap
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/versecheck/66)
=> updated verse check check boxes again

Container.js
Follow the instructions and ensure that the previous bug does not occur.
The below behavior is now fixed, see *
- Open a project in tW and make a selection.
- Click Save Changes
- Click Edit, copy all of the text to the clipboard, delete all of the verse text, and then check the Other box
- Click Save Changes, then Save Blank Verse, and then OK.
- Click Edit, paste the text back in, then click the Other box
- Click Save Changes
- Notice that the previously selected text no longer shows as being selected.
- Click Select
- *Notice that the previously selected text again shows as being selected in the Edit box
- Click Cancel
- Notice that the previously selected text no longer shows as being selected.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" …
=> Reload state selections on mode change and minor syntax refactor

Container.js
This PR utilizes the new filtering function in the usfm module to remove extra, unneeded tags.
Checkout branch ```enhancement/jay/filter-footnotes/1941```
on Scripture Pane, and Verse Check (this is assuming the usfm latetest module with the filtering function has already been merged with develop)
and open an eph book on tN and find the check for 1:1 and ensure there are no footnotes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/versecheck/76)
=> New Filtering Function To Remove Specified Markers

Container.js
This PR adds functionality to check for using a string vs. an array in the render method.
I believe the PR in the usfm-js module is a requirement for this to function properly
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/versecheck/77)
=> Added Fixes For Handling USFM 3 formatted Bibles

src/components/EditVerseArea.js
Open verse check and make sure the word choice text is not wrapped.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/versecheck/80)
=> Fixed Word Wrap On Edit Mode

src/Container.js
- Verify that verse check is not default to Select mode when the verse is blank
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/versecheck/79)
=> Not defaulting to Select mode when the verse is blank

__tests__/MyLanguageModal.test.js, package.json, src/components/DefaultArea.js, src/components/MyLanguageModal.js, src/css/Style.js
Addresses Issue https://github.com/unfoldingWord-dev/translationCore/issues/1279 for the expanded my language's title
Go to tW tool for a project and in "Step 2" expand the scripture of the selected verse to view the chapter. The title of the modal should be the name of the Bible book.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/versecheck/82)
=> Feature - #1279 - Adds titles to expanded target language pane

src/components/DefaultArea.js
- Moved selection checking out of tool.  It is now in tCore action to support all editors.
- test as part of https://github.com/unfoldingWord-dev/translationCore/pull/4283
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/versecheck/102)
=> Feature 3086/show invalidated selection
